version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL="mysql://root:root@db:3306/qp-assesment?schema=public"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qp-assesment
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
